---
- name: Install and configure Traefik
  # replace with yours
  hosts: ondeu
  become: yes

  vars:
    src_dir: ../traefik/
    dst_dir: /opt/docker/traefik

  tasks:
    - name: Copy configs
      copy: 
        src: "{{ src_dir }}"
        dest: "{{ dst_dir }}"
        mode: 0555

    - name: Create network
      shell:
        cmd: "docker network create traefik"

    - name: Start service
      shell:
        cmd: "docker-compose -f {{ dst_dir }}/docker-compose.yml up -d"
