version: "3.6"

services:
  postgres:
    image: postgres:14
    ports: 
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - ./data/master:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DBNAME}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak -h 127.0.0.1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    restart: unless-stopped

  backups:
    image: postgres:14
    # Database backups prune interval (replace with yours). Default is 7 days.
    # find /srv/keycloak-postgres/backups -type f -mtime +7 | xargs rm -f

    # Keycloak backups interval (replace with yours). Default is 1 day.
    # sleep 24h

    # Run keycloak-restore-database.sh to restore database if needed.
    command: sh -c 'sleep 30m
             && while true; do
             PGPASSWORD="$$(echo $$POSTGRES_PASSWORD)"
             pg_dump
             -h postgres
             -p 5432
             -d keycloak
             -U keycloak | gzip > /srv/keycloak-postgres/backups/keycloak-postgres-backup-$$(date "+%Y-%m-%d_%H-%M").gz
             && find /srv/keycloak-postgres/backups -type f -mtime +7 | xargs rm -f;
             sleep 24h; done'
    volumes:
      - ./data/backup:/srv/keycloak-postgres/backups
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    restart: unless-stopped
    depends_on:
      - postgres

networks:
  default:
    external:
      name: traefik